[SO-34] feat: 카카오 소셜로그인으로 회원가입 처리
SWM-Space-Odyssey/WeddingMate_BackEnd pull request #10
Opened 2023-07-17 04:39 UTC by nitronium102

### 작업 개요
카카오 소셜 로그인 적용 후 자동 회원가입 처리

### 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경

### 작업 상세 내용
[domain]
- User 관련 entity 생성
- OAuth2 관련 provider, service, handler 추가

[global]
- Security 관련 configure settings, handler 추가
- User 관련 exception 추가
- OAuth2 관련 exception 추가
- User, OAuth2 관련 response constant 추가

### 생각해볼 문제
- token 관련 database를 redis로 이전해야 함
- 프론트엔드와 연결할 때 link 추후 추가

2023-07-17 05:07 UTC, lina1919 requested changes

2023-07-17 05:07 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/UserEnum.java
> +package swmaestro.spaceodyssey.weddingmate.domain.users.entity;
이건 Enum 폴더를 따로 안만드는 건가요?

2023-07-18 04:47 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/UserEnum.java
> +package swmaestro.spaceodyssey.weddingmate.domain.users.entity;
생성하겠습니다~!

2023-07-18 05:52 UTC, lina1919 commented
LGTM!
수고 많으셨습니다. github secrets에 환경변수들만 업데이트 해서 넣어주고 merge 하면 될 것 같아요~!

2023-07-18 05:54 UTC, lina1919 approved these changes
LGTM!
수고 많으셨습니다. github secrets에 환경변수들만 업데이트 해서 넣어주고 merge 하면 될 것 같아요~!

2023-07-18 05:56 UTC, nitronium102 commented
[SO-34] feat: 카카오 소셜로그인 회원가입 추가

2023-07-18 05:57 UTC, merged