[SO-287] refactor : serviceImpl 패턴으로 likeService 개선
SWM-Space-Odyssey/WeddingMate_BackEnd pull request #128
Opened 2023-10-16 04:42 UTC by lina1919

### 작업 개요
- serviceImpl 패턴으로 likeService 개선

### 작업 분류
- [ ] 버그 수정
- [ ] 신규 기능
- [x] 프로젝트 구조 변경

### 작업 상세 내용
1. likeService 클래스 interface로 변경 
2. likeService의 구현체를 각각 plannerLikeImpl, itemLikeImpl, companyLikeImpl, portfolioLikeImpl로 나눔
3. Spring DI에 의존하여 map을 통해 자동으로 주입된 service 클래스를 상황에 맞추어 사용

### 생각해볼 문제
- 드디어 commit log가 깨끗해졌습니다...

2023-10-17 08:05 UTC, nitronium102 approved these changes
확인했습니다~! 확실히 중복 코드가 많이 줄어든 것 같아요

2023-10-17 08:05 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
>  	}
이렇게도 할 수 있네요 새로 알아갑니다👍👍

2023-10-17 12:28 UTC, nitronium102 requested changes

2023-10-17 12:28 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
> -@Tag(name = "Like API", description = "좋아요 관련 API")
위에 tag는 swagger에 표시되는 용도입니다! 이것만 포함해서 다시 커밋해주세욥

2023-10-17 12:41 UTC, cobi-ahn commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
> +	public ApiResponse<Object> getUserLiked(@AuthUsers Users users, @NotNull @PathVariable("service") LikeEnum service) {
'users' table
UserEntity UserController

@AuthUsers User user

2023-10-17 12:42 UTC, cobi-ahn commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
> +	public ApiResponse<Object> getUserLiked(@AuthUsers Users users, @NotNull @PathVariable("service") LikeEnum service) {
@RequestMapping("/api/v1/likes/{userId}")
@RequestMapping("/api/v1/likes/by-user-id/{userId}")

2023-10-17 12:45 UTC, cobi-ahn commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
> +	public ApiResponse<Object> getUserLiked(@AuthUsers Users users, @NotNull @PathVariable("service") LikeEnum service) {
bff (gateway) - api server << 
api server > restful api url
URL만 보더라도 어떤 역할을 하는지

2023-10-17 12:47 UTC, cobi-ahn commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
> +	public ApiResponse<Object> getUserLiked(@AuthUsers Users users, @NotNull @PathVariable("service") LikeEnum service) {
/api/v1/likes/by-user-id
/api/v1/user-likes

2023-10-17 12:50 UTC, cobi-ahn commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
> +		Boolean isLiked = likesService.like(likeReqDto.getId(), users, likeReqDto.getLikeType());
like, unlike 
한가지 역할을 담당해야함

2023-10-17 12:52 UTC, cobi-ahn commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/dto/LikeReqDto.java
>  @NoArgsConstructor(access = AccessLevel.PROTECTED)
DEFAULT (같은 패키지에서 접근 허용)

2023-10-17 13:05 UTC, cobi-ahn commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/PortfolioLikeImpl.java
> +			portfolios.setLikeCount(portfolios.getLikeCount() - 1);
-1 ??  > 0 조건 필요하지 않을지 ?

2023-10-19 04:58 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
> +	@PostMapping()
불필요한 따옴표 삭제하였습니다.

2023-10-19 04:59 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesService.java
> +	void decreaseLikeCount(String lockName, Long id, boolean isIncrement);
LikeService에서 increaseLikeCount와 decreaseLikeCount를 분리하였습니다.

2023-10-19 05:00 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planners.java
> +		}
각 클래스에 validate 메소드를 추가하였습니다.

2023-10-19 05:26 UTC, nitronium102 approved these changes
많이 바뀌었네요~!! 수고하셨습니다

2023-10-19 05:56 UTC, merged