[SO-303] feat: 신고 기능에 분산락 추가
SWM-Space-Odyssey/WeddingMate_BackEnd pull request #144
Opened 2023-11-06 05:53 UTC by nitronium102

### 작업 개요
신고 기능에 분산락 추가

### 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경

### 작업 상세 내용

### 생각해볼 문제

2023-11-06 05:55 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionService.java
>  	}
원래는 user를 받아서 바로 incrementReportCnt()를 진행하였습니다.
하지만 분산락을 사용함에 따라 @Transactional을 사용할 수 없었고, 따라서 영속성이 전이되지 않아 바뀐 객체의 상태가 db까지 전달되지 않았습니다.
따라서 addReportCnt 함수 안에서 id로 user를 호출함으로서 영속성 컨텍스트 안에서 객체가 관리되도록 설정하였습니다 (하지만 더 좋은 방법이 있을 것 같습니다...)

2023-11-06 06:58 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionService.java
>  	}
네 확인하였습니다.
다만 분산락을 사용했을 때 사용한 함수에 대해서 분산락 annotation과 이중으로 @Transactional을 사용할 수 없는 것이지 다른 함수에는 사용이 가능해서 지금 주석처리한 @Transactional 을 주석처리 해제하고 테스트 코드 돌리면 잘 동작하네요.
@Transactional 주석 처리를 해제하고 다시 올리면 좋을 것 같습니다.

2023-11-06 07:01 UTC, lina1919 requested changes
주석처리만 해제해주세요~!

2023-11-06 07:01 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionService.java
> +	//@Transactional
직접적으로 분산락을 거는 함수가 아닌 다른 메소드들에서는 @Transactional 어노테이션이 사용가능한 것으로 확인됩니다. 테스트코드도 문제없고요.
이와같은 메소드들에 주석처리 해제해주세요!

2023-11-06 07:01 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionService.java
> +	//@Transactional
주석처리 해제

2023-11-06 07:01 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionService.java
> +	//	@Transactional
주석처리 해제

2023-11-06 07:01 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionService.java
> +	//@Transactional
주석처리 해제

2023-11-06 07:01 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionService.java
> +	//@Transactional
주석처리 해제

2023-11-06 14:25 UTC, nitronium102 reviewed
해당 상황에서 자식 객체에 @Transactional을 적용할 경우, 테스트 코드 상에서는 잘 작동하지만 실제 코드에서는 transaction self-invocation 에러가 발생합니다. (SonarLint 오류 및 IntelliJ 알림)

self-invocation 에러란 트랜잭션이 적용되는 메서드가 동일한 클래스의 다른 메서드를 호출하는 것을 말하는데 이 경우에는 @Transactional 어노테이션이 적용되어 있더라도 실제로 트랜잭션이 적용되지 않습니다. 

Spring은 메서드 또는 클래스에 @Transactional이 달린 클래스들에 대한 proxy를 생성합니다. 그리고 트랜잭션 적용을 위해 프록시를 통해 호출하는 메서드만 인터셉트합니다. 동일한 bean에 있는 메서드라면 프록시를 통해 호출하는 것이 아닙니다. 

내부 메서드를 호출한다는 것은 this.메서드()를 호출한 것과 같은 의미입니다. this는 프록시가 아닌 원본 객체, 타깃을 의미하는 것이므로 프록시가 적용되지 않습니다.
(https://cheese10yun.github.io/spring-transacion-same-bean/)

따라서 `transactional` 어노테이션을 추가하지 않아도 `UserSuspensionService` 안의 객체들이 동일한 트랜잭션에서 실행될 것이라 생각했습니다. 
이를 검증하기 위해 출력문을 추가하여, `UserSuspensionService`의 함수들이 모두 동일한 트랜잭션 안에 있는지 확인해보았습니다. 그 결과 모두 하나의 transaction 안에서 동작하는 것을 확인하였습니다. 따라서 굳이 `transactional` 어노테이션을 추가하지 않아도 하나의 transaction으로 묶여 적용될 것으로 생각됩니다.
![image](https://github.com/SWM-Space-Odyssey/WeddingMate_BackEnd/assets/68282057/187bc527-c133-4a02-a846-59cefb88730b)

2023-11-08 02:53 UTC, lina1919 requested changes
네 상세한 설명 감사드립니다. sonarcloud 코드 스멜에서 logger 삭제하라는 것만 삭제해주시면 될 것 같습니다.

2023-11-09 05:09 UTC, lina1919 approved these changes
네 수고하셨습니다! 머지하시죠 :)

2023-11-09 05:10 UTC, merged