[SO-93] feat : portfolio 생성, 조회 기능 추가
SWM-Space-Odyssey/WeddingMate_BackEnd pull request #26
Opened 2023-07-23 12:04 UTC by lina1919

### 작업 개요
포트폴리오 생성, 조회 api 추가

### 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경

### 작업 상세 내용
1. 포트폴리오 생성 api 추가
2. 포트폴리오 조회 api 추가

### 생각해볼 문제
- 새로운 태그 입력 시 이를 생성하는 코드를 추후 추가하여야함
- 이미지 관련된 설정 및 기능을 추후 추가하여야함

2023-07-23 12:51 UTC, nitronium102 requested changes
repository 부분만 수정해주시면 될 것 같아요
주말까지 수고하셨습니다!!👍👍👍

2023-07-23 12:51 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/repository/CategoryRepository.java
> +}
p2. JpaRepository를 extend 한 경우에는 스프링에서 자동으로 인식해주기 때문에 @Repository 어노테이션을 붙일 필요가 없습니다!
https://stackoverflow.com/questions/44069367/repository-not-necessary-when-implementing-jparepository

2023-07-23 12:51 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
> +	}
p3. @AuthUsers에 의해서 user 구분이 되기 때문에 그냥 @GetMapping("/")로 해도 괜찮을 것 같습니다!

2023-07-23 12:51 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
> +		return ResponseEntity.ok().body(HttpStatus.CREATED);
p3. item 관련 api가 많이 생긴다면 따로 controller로 빼는 것도 좋을 것 같습니다!

2023-07-23 12:51 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/ItemSaveReqDto.java
> +	private List<String> itemTagList;
p3. enum으로 받는 방법도 있으니 나중에 아래 링크 참고해보셔도 좋을 것 같아요! 다만 저희는 유저가 입력한 값도 받아오니 조금 더 고민이 필요할 것 같긴 합니다
https://green-bin.tistory.com/90

2023-07-23 12:51 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/repository/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
p2. 여기도 위와 동일합니다~!

2023-07-23 12:51 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/repository/PortfolioRepository.java
> +
p2. 여기도 위와 동일합니다~!

2023-07-23 14:22 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/entity/Tag.java
> +	}
현재 planner, customer 회원가입을 만들고 있는데, plannerTag, customerTag도 필드에 계속해서 추가될 것 같네요....ERD...안멘께 먼저 보내서 여쭤볼까요?

2023-07-23 14:28 UTC, nitronium102 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/entity/Tag.java
> +	}
그리고 현재 portfolio와 tag 둘 다에서 porfolioTag에 대해 cascade 권한을 갖고 있는데, cascade.ALL은 완전히 개인 소유인 관계에 대해서 적용하는 것이 좋습니다.
이처럼 portfolioTag가 공동소유일 경우에는 portfolio와 tag 둘 중 한 쪽에서만 cascade를 사용해야 한다고 합니다!
https://resilient-923.tistory.com/417

2023-07-24 01:33 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/repository/CategoryRepository.java
> +}
오 그렇군요! 수정하도록 하겠습니다

2023-07-24 01:35 UTC, lina1919 commented on src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/entity/Tag.java
> +	}
네 안멘한테 erd 관련 부분 확인받는 것이 좋을 듯 합니다.
그리고 삭제권한은 portfolio에게 있는 것이 맞을 것 같네요. 이 부분도 수정하여 반영하도록 하겠습니다!

2023-07-24 02:23 UTC, lina1919 commented
수정 사항 반영했으니 확인 부탁드립니다!

2023-07-24 02:39 UTC, nitronium102 approved these changes
변경 사항 많았는데 수고하셨습니다!! conflict 해결하고 머지하시죠ㅎㅎㅎ

2023-07-24 03:15 UTC, merged